global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: kafka-brokers
    static_configs:
      - targets:
          - kafka_broker_1:7071
          - kafka_broker_2:7071
          - kafka_broker_3:7071
